title: Jinbo Wang's Homepage
page-top-title: A.K.A. TheBunniest's Rabbit Hole
top-section-bg-text: Welcome to Jinbo Wang's Homepage ;)
home-subtitle: Jinbo Wang&ensp;|&ensp;TheBunniest&ensp;|&ensp;王劲博
copyright-text: '&copy; senli1073 2023-2024. All Rights Reserved.'
