title: Jinbo Wang's Homepage
page-top-title: Jinbo Wang
top-section-bg-text: Computational Biology and Bioinformatics!
home-subtitle: Jinbo Wang&ensp;|&ensp;TheBunniest&ensp;|&ensp;王劲博
copyright-text: '&copy; 王劲博 2024-2025. All Rights Reserved.'
