title: Jinbo Wang's Homepage
page-top-title: Jinbo Wang
top-section-bg-text: Welcome to Jinbo Wang's Homepage, a.k.a. TheBunniest's Rabbit Hole :)
home-subtitle: Jinbo Wang&ensp;|&ensp;TheBunniest&ensp;|&ensp;王劲博
copyright-text: '&copy; senli1073 2023-2024. All Rights Reserved.'
