title: Jinbo Wang's Homepage
page-top-title: Jinbo Wang
top-section-bg-text: Computational Biology and Bioinformatics!
home-subtitle: Jinbo Wang&ensp;|&ensp;TheBunniest&ensp;|&ensp;王劲博
copyright-text: '&copy; senli1073 2023-2024. All Rights Reserved.'
